# Generated by Django 2.2 on 2019-04-28 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years', models.PositiveSmallIntegerField(choices=[(2024, '2024/2025'), (2023, '2023/2024'), (2022, '2022/2023'), (2021, '2021/2022'), (2020, '2020/2021'), (2019, '2019/2020'), (2018, '2018/2019'), (2017, '2017/2018'), (2016, '2016/2017'), (2015, '2015/2016'), (2014, '2014/2015'), (2013, '2013/2014'), (2012, '2012/2013'), (2011, '2011/2012'), (2010, '2010/2011'), (2009, '2009/2010'), (2008, '2008/2009'), (2007, '2007/2008'), (2006, '2006/2007'), (2005, '2005/2006'), (2004, '2004/2005'), (2003, '2003/2004'), (2002, '2002/2003'), (2001, '2001/2002'), (2000, '2000/2001'), (1999, '1999/2000'), (1998, '1998/1999'), (1997, '1997/1998'), (1996, '1996/1997'), (1995, '1995/1996'), (1994, '1994/1995'), (1993, '1993/1994'), (1992, '1992/1993'), (1991, '1991/1992'), (1990, '1990/1991'), (1989, '1989/1990'), (1988, '1988/1989'), (1987, '1987/1988'), (1986, '1986/1987'), (1985, '1985/1986'), (1984, '1984/1985'), (1983, '1983/1984'), (1982, '1982/1983'), (1981, '1981/1982'), (1980, '1980/1981'), (1979, '1979/1980'), (1978, '1978/1979'), (1977, '1977/1978'), (1976, '1976/1977'), (1975, '1975/1976'), (1974, '1974/1975'), (1973, '1973/1974'), (1972, '1972/1973'), (1971, '1971/1972'), (1970, '1970/1971'), (1969, '1969/1970'), (1968, '1968/1969'), (1967, '1967/1968'), (1966, '1966/1967'), (1965, '1965/1966'), (1964, '1964/1965'), (1963, '1963/1964'), (1962, '1962/1963'), (1961, '1961/1962'), (1960, '1960/1961'), (1959, '1959/1960'), (1958, '1958/1959'), (1957, '1957/1958'), (1956, '1956/1957'), (1955, '1955/1956'), (1954, '1954/1955'), (1953, '1953/1954'), (1952, '1952/1953'), (1951, '1951/1952'), (1950, '1950/1951'), (1949, '1949/1950'), (1948, '1948/1949'), (1947, '1947/1948'), (1946, '1946/1947'), (1945, '1945/1946'), (1944, '1944/1945'), (1943, '1943/1944'), (1942, '1942/1943'), (1941, '1941/1942'), (1940, '1940/1941'), (1939, '1939/1940'), (1938, '1938/1939'), (1937, '1937/1938'), (1936, '1936/1937'), (1935, '1935/1936'), (1934, '1934/1935'), (1933, '1933/1934'), (1932, '1932/1933'), (1931, '1931/1932'), (1930, '1930/1931'), (1929, '1929/1930'), (1928, '1928/1929'), (1927, '1927/1928'), (1926, '1926/1927'), (1925, '1925/1926'), (1924, '1924/1925'), (1923, '1923/1924'), (1922, '1922/1923'), (1921, '1921/1922'), (1920, '1920/1921'), (1919, '1919/1920'), (1918, '1918/1919'), (1917, '1917/1918'), (1916, '1916/1917'), (1915, '1915/1916'), (1914, '1914/1915'), (1913, '1913/1914'), (1912, '1912/1913'), (1911, '1911/1912'), (1910, '1910/1911'), (1909, '1909/1910'), (1908, '1908/1909'), (1907, '1907/1908'), (1906, '1906/1907'), (1905, '1905/1906'), (1904, '1904/1905'), (1903, '1903/1904'), (1902, '1902/1903'), (1901, '1901/1902'), (1900, '1900/1901')], default=2024, verbose_name='Year')),
                ('semester', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2)], default=1, verbose_name='Number')),
            ],
            options={
                'verbose_name': 'Curriculum',
                'verbose_name_plural': 'Curriculums',
            },
        ),
        migrations.CreateModel(
            name='GroupState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Name')),
                ('suffix', models.CharField(blank=True, max_length=16, unique=True, verbose_name='Suffix')),
                ('semesters', models.PositiveSmallIntegerField(default=8, verbose_name='Number of semesters')),
                ('priority', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=5, verbose_name='Priority')),
            ],
            options={
                'verbose_name': 'Group state',
                'verbose_name_plural': 'Group states',
            },
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(unique=True, verbose_name='Number')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Name')),
                ('abbreviation', models.CharField(max_length=50, unique=True, verbose_name='Abbreviation')),
            ],
            options={
                'verbose_name': 'Specialty',
                'verbose_name_plural': 'Specialties',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
            },
        ),
        migrations.CreateModel(
            name='CurriculumSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lections', models.PositiveSmallIntegerField(default=1, verbose_name='Number of lections')),
                ('curriculum', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='timetableapp.Curriculum', verbose_name='Curriculum')),
                ('subject', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='timetableapp.Subject', verbose_name='Subject')),
            ],
            options={
                'verbose_name': 'Curriculum for subject',
                'verbose_name_plural': 'Curriculum for subjects',
                'unique_together': {('subject', 'curriculum')},
            },
        ),
        migrations.AddField(
            model_name='curriculum',
            name='specialty',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='timetableapp.Specialty', verbose_name='Specialty'),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='subjects',
            field=models.ManyToManyField(through='timetableapp.CurriculumSubject', to='timetableapp.Subject', verbose_name='Curriculum for subject'),
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(choices=[(2019, 2019), (2018, 2018), (2017, 2017), (2016, 2016), (2015, 2015), (2014, 2014), (2013, 2013), (2012, 2012), (2011, 2011), (2010, 2010), (2009, 2009), (2008, 2008), (2007, 2007), (2006, 2006), (2005, 2005), (2004, 2004), (2003, 2003), (2002, 2002), (2001, 2001), (2000, 2000), (1999, 1999), (1998, 1998), (1997, 1997), (1996, 1996), (1995, 1995), (1994, 1994), (1993, 1993), (1992, 1992), (1991, 1991), (1990, 1990), (1989, 1989), (1988, 1988), (1987, 1987), (1986, 1986), (1985, 1985), (1984, 1984), (1983, 1983), (1982, 1982), (1981, 1981), (1980, 1980), (1979, 1979), (1978, 1978), (1977, 1977), (1976, 1976), (1975, 1975), (1974, 1974), (1973, 1973), (1972, 1972), (1971, 1971), (1970, 1970), (1969, 1969), (1968, 1968), (1967, 1967), (1966, 1966), (1965, 1965), (1964, 1964), (1963, 1963), (1962, 1962), (1961, 1961), (1960, 1960), (1959, 1959), (1958, 1958), (1957, 1957), (1956, 1956), (1955, 1955), (1954, 1954), (1953, 1953), (1952, 1952), (1951, 1951), (1950, 1950), (1949, 1949), (1948, 1948), (1947, 1947), (1946, 1946), (1945, 1945), (1944, 1944), (1943, 1943), (1942, 1942), (1941, 1941), (1940, 1940), (1939, 1939), (1938, 1938), (1937, 1937), (1936, 1936), (1935, 1935), (1934, 1934), (1933, 1933), (1932, 1932), (1931, 1931), (1930, 1930), (1929, 1929), (1928, 1928), (1927, 1927), (1926, 1926), (1925, 1925), (1924, 1924), (1923, 1923), (1922, 1922), (1921, 1921), (1920, 1920), (1919, 1919), (1918, 1918), (1917, 1917), (1916, 1916), (1915, 1915), (1914, 1914), (1913, 1913), (1912, 1912), (1911, 1911), (1910, 1910), (1909, 1909), (1908, 1908), (1907, 1907), (1906, 1906), (1905, 1905), (1904, 1904), (1903, 1903), (1902, 1902), (1901, 1901), (1900, 1900)], default=2019, verbose_name='Year')),
                ('number', models.PositiveSmallIntegerField(choices=[(9, 9), (8, 8), (7, 7), (6, 6), (5, 5), (4, 4), (3, 3), (2, 2), (1, 1)], default=1, verbose_name='Number')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='timetableapp.Specialty', verbose_name='Specialty')),
                ('state', models.ForeignKey(default={'priority': 1}, on_delete=django.db.models.deletion.PROTECT, to='timetableapp.GroupState', verbose_name='State')),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
                'unique_together': {('specialty', 'state', 'year')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='curriculum',
            unique_together={('specialty', 'years')},
        ),
    ]
