# Generated by Django 2.2 on 2019-04-28 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetableapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='parentId',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='timetableapp.Group', verbose_name='Parent group class'),
        ),
    ]
