# Generated by Django 2.2 on 2019-05-01 12:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetableapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semesterschedule',
            name='semester',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Semester'),
        ),
    ]
