# Generated by Django 2.2 on 2019-05-01 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetableapp', '0002_specialty_department'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialty',
            options={'ordering': ['number', 'name'], 'verbose_name': 'Specialty', 'verbose_name_plural': 'Specialties'},
        ),
    ]
