# Generated by Django 2.2 on 2019-04-28 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetableapp', '0002_group_parentid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='number',
            field=models.PositiveSmallIntegerField(choices=[(9, 9), (8, 8), (7, 7), (6, 6), (5, 5), (4, 4), (3, 3), (2, 2), (1, 1)], default=None, null=True, verbose_name='Number'),
        ),
        migrations.AlterField(
            model_name='group',
            name='parentId',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='timetableapp.Group', verbose_name='Parent group class'),
        ),
    ]
