# Generated by Django 2.2 on 2019-05-01 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetableapp', '0003_auto_20190501_1850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialty',
            name='department',
        ),
        migrations.AddField(
            model_name='specialty',
            name='faculty',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='timetableapp.Faculty', verbose_name='Faculty'),
        ),
    ]
