# Generated by Django 2.2 on 2019-04-28 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetableapp', '0004_auto_20190428_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='number',
            field=models.PositiveSmallIntegerField(choices=[(None, '-'), (8, 8), (7, 7), (6, 6), (5, 5), (4, 4), (3, 3), (2, 2), (1, 1)], default=None, null=True, verbose_name='Number'),
        ),
    ]
