# Generated by Django 2.2 on 2019-05-02 11:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetableapp', '0004_auto_20190501_1934'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialty',
            options={'verbose_name': 'Specialty', 'verbose_name_plural': 'Specialties'},
        ),
        migrations.AlterField(
            model_name='groupstream',
            name='year',
            field=models.PositiveSmallIntegerField(default=2019, validators=[django.core.validators.MinValueValidator(1900)], verbose_name='Year'),
        ),
    ]
