# Generated by Django 2.2 on 2019-04-28 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetableapp', '0005_auto_20190428_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='number',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(None, '-'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)], default=None, null=True, verbose_name='Number'),
        ),
        migrations.AlterUniqueTogether(
            name='group',
            unique_together={('parentId', 'specialty', 'year', 'state', 'number')},
        ),
    ]
