# Generated by Django 2.2 on 2019-05-02 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetableapp', '0006_auto_20190502_1114'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formofstudy',
            options={'ordering': ['priority'], 'verbose_name': 'Form of study', 'verbose_name_plural': 'Forms of study'},
        ),
    ]
