# Generated by Django 2.2 on 2019-04-28 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetableapp', '0006_auto_20190428_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='number',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '-'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)], default=1, verbose_name='Number'),
        ),
        migrations.AlterField(
            model_name='group',
            name='parentId',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='timetableapp.Group', verbose_name='Parent group class'),
        ),
    ]
