# Generated by Django 2.2 on 2019-04-28 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetableapp', '0008_auto_20190428_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='number',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(None, '-'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)], default=None, verbose_name='Number'),
        ),
    ]
