# Generated by Django 2.2 on 2019-05-02 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetableapp', '0008_auto_20190502_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='formofstudy',
            name='end_date_first',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='End date for first semester'),
        ),
        migrations.AddField(
            model_name='formofstudy',
            name='end_date_second',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='End date for second semester'),
        ),
        migrations.AddField(
            model_name='formofstudy',
            name='start_date_first',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Start date for first semester'),
        ),
        migrations.AddField(
            model_name='formofstudy',
            name='start_date_second',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Start date for second semester'),
        ),
    ]
