# Generated by Django 2.2 on 2019-05-03 09:13

from django.db import migrations, models
import timetableapp.models
import timetableapp.settings
import yearlessdate.models


class Migration(migrations.Migration):

    dependencies = [
        ('timetableapp', '0010_auto_20190502_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formofstudy',
            name='end_date_first',
            field=yearlessdate.models.YearlessDateField(blank=True, default=None, null=True, verbose_name='Default end date for first semester'),
        ),
        migrations.AlterField(
            model_name='formofstudy',
            name='end_date_second',
            field=yearlessdate.models.YearlessDateField(blank=True, default=None, null=True, verbose_name='Default end date for second semester'),
        ),
        migrations.AlterField(
            model_name='formofstudy',
            name='start_date_first',
            field=yearlessdate.models.YearlessDateField(blank=True, default=None, null=True, verbose_name='Default start date for first semester'),
        ),
        migrations.AlterField(
            model_name='formofstudy',
            name='start_date_second',
            field=yearlessdate.models.YearlessDateField(blank=True, default=None, null=True, verbose_name='Default start date for second semester'),
        ),
        migrations.AlterField(
            model_name='groupstream',
            name='year',
            field=models.PositiveSmallIntegerField(default=timetableapp.settings.current_year, validators=[timetableapp.models.year_min_value, timetableapp.models.year_max_value], verbose_name='Year'),
        ),
    ]
