# Generated by Django 2.2 on 2019-04-28 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetableapp', '0010_auto_20190428_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculumsubject',
            name='group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='timetableapp.Group', verbose_name='Group'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curriculumsubject',
            name='independentWork',
            field=models.PositiveSmallIntegerField(default=None, verbose_name='Amound of independent work'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curriculumsubject',
            name='laboratory',
            field=models.PositiveSmallIntegerField(default=None, verbose_name='Number of laboratory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curriculumsubject',
            name='lectures',
            field=models.PositiveSmallIntegerField(default=None, verbose_name='Number of lectures'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curriculumsubject',
            name='practices',
            field=models.PositiveSmallIntegerField(default=None, verbose_name='Number of practices'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curriculumsubject',
            name='semester',
            field=models.PositiveSmallIntegerField(default=None, verbose_name='Semester'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='curriculumsubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetableapp.Subject', verbose_name='Subject'),
        ),
        migrations.AlterUniqueTogether(
            name='curriculumsubject',
            unique_together={('group', 'semester', 'subject')},
        ),
        migrations.AlterUniqueTogether(
            name='group',
            unique_together={('specialty', 'year', 'state', 'parentId', 'number')},
        ),
        migrations.RemoveField(
            model_name='curriculumsubject',
            name='curriculum',
        ),
        migrations.RemoveField(
            model_name='curriculumsubject',
            name='lections',
        ),
        migrations.DeleteModel(
            name='Curriculum',
        ),
    ]
