# Generated by Django 2.2 on 2019-04-28 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetableapp', '0011_auto_20190428_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculumsubject',
            name='independentWork',
            field=models.PositiveSmallIntegerField(verbose_name='Amount of independent work'),
        ),
    ]
