# Generated by Django 2.2 on 2019-05-03 09:39

from django.db import migrations
import yearlessdate.models


class Migration(migrations.Migration):

    dependencies = [
        ('timetableapp', '0011_auto_20190503_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='formofstudy',
            name='date_first',
            field=yearlessdate.models.YearlessDateRangeField(blank=True, default=None, null=True, verbose_name='Default time interval for first semester'),
        ),
        migrations.AddField(
            model_name='formofstudy',
            name='date_second',
            field=yearlessdate.models.YearlessDateRangeField(blank=True, default=None, null=True, verbose_name='Default time interval for second semester'),
        ),
    ]
