# Generated by Django 2.2 on 2019-05-03 10:03

from django.db import migrations, models
import django.db.models.deletion
import yearlessdate.models


class Migration(migrations.Migration):

    dependencies = [
        ('timetableapp', '0012_auto_20190503_0939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formofstudy',
            name='date_first',
        ),
        migrations.RemoveField(
            model_name='formofstudy',
            name='date_second',
        ),
        migrations.RemoveField(
            model_name='formofstudy',
            name='end_date_first',
        ),
        migrations.RemoveField(
            model_name='formofstudy',
            name='end_date_second',
        ),
        migrations.RemoveField(
            model_name='formofstudy',
            name='start_date_first',
        ),
        migrations.RemoveField(
            model_name='formofstudy',
            name='start_date_second',
        ),
        migrations.CreateModel(
            name='FormOfStudySemester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_range', yearlessdate.models.YearlessDateRangeField(blank=True, default=None, null=True, verbose_name='Default time interval for first semester')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='timetableapp.FormOfStudy', verbose_name='Form of study')),
            ],
            options={
                'verbose_name': 'Semester',
                'verbose_name_plural': 'Semesters',
            },
        ),
    ]
