# Generated by Django 2.2 on 2019-04-28 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetableapp', '0012_auto_20190428_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Name')),
                ('abbreviation', models.CharField(blank=True, default=None, max_length=128, null=True, unique=True, verbose_name='Abbreviation')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Name')),
                ('abbreviation', models.CharField(blank=True, default=None, max_length=128, null=True, unique=True, verbose_name='Abbreviation')),
            ],
            options={
                'verbose_name': 'Faculty',
                'verbose_name_plural': 'Faculties',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=128, verbose_name='First name')),
                ('middleName', models.CharField(max_length=128, verbose_name='First name')),
                ('lastName', models.CharField(max_length=128, verbose_name='First name')),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'Persons',
                'unique_together': {('firstName', 'middleName', 'lastName')},
            },
        ),
        migrations.AlterModelOptions(
            name='curriculumsubject',
            options={'verbose_name': 'Curriculum for subject', 'verbose_name_plural': 'Curriculums for subject'},
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='timetableapp.Department', verbose_name='Department')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='timetableapp.Person', verbose_name='Person')),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teachers',
            },
        ),
        migrations.AddField(
            model_name='department',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='timetableapp.Faculty', verbose_name='Faculty'),
        ),
    ]
