# Generated by Django 2.2 on 2019-04-28 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetableapp', '0013_auto_20190428_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='lastName',
            field=models.CharField(max_length=128, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='middleName',
            field=models.CharField(max_length=128, verbose_name='Middle name'),
        ),
    ]
