# Generated by Django 2.2 on 2019-04-28 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetableapp', '0014_auto_20190428_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculumsubject',
            name='department',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='timetableapp.Department', verbose_name='Department'),
        ),
    ]
