# Generated by Django 2.2 on 2019-04-28 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetableapp', '0015_curriculumsubject_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curriculumsubject',
            name='department',
        ),
        migrations.AddField(
            model_name='curriculumsubject',
            name='lecturer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='timetableapp.Teacher', verbose_name='Lecturer'),
        ),
    ]
