# Generated by Django 2.2 on 2019-05-03 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetableapp', '0016_auto_20190503_1520'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GroupSemester',
            new_name='GroupStreamSemester',
        ),
        migrations.AlterModelOptions(
            name='groupstreamsemester',
            options={'verbose_name': 'Group stream semester', 'verbose_name_plural': 'Group stream semesters'},
        ),
    ]
