# Generated by Django 2.2 on 2019-04-28 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetableapp', '0016_auto_20190428_2002'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CurriculumSubject',
            new_name='CurriculumEntry',
        ),
    ]
