# Generated by Django 2.2 on 2019-04-28 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetableapp', '0017_auto_20190428_2005'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curriculumentry',
            options={'verbose_name': 'Curriculum entry', 'verbose_name_plural': 'Curriculum entries'},
        ),
        migrations.AddField(
            model_name='curriculumentry',
            name='subject',
            field=models.ManyToManyField(to='timetableapp.Subject', verbose_name='Subject'),
        ),
        migrations.AlterUniqueTogether(
            name='curriculumentry',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='curriculumentry',
            name='subject',
        ),
    ]
