# Generated by Django 2.2 on 2019-04-28 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetableapp', '0019_curriculumentry_subject1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curriculumentry',
            old_name='subject',
            new_name='subjects',
        ),
    ]
