# Generated by Django 2.2 on 2019-04-28 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetableapp', '0020_auto_20190428_2027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curriculumentry',
            name='lecturer',
        ),
        migrations.CreateModel(
            name='CurriculumEntrySubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetableapp.CurriculumEntry', verbose_name='Curriculum entry')),
                ('lecturer', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='timetableapp.Teacher', verbose_name='Lecturer')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetableapp.Subject', verbose_name='Subject')),
            ],
            options={
                'verbose_name': 'Subject for curriculum entry',
                'verbose_name_plural': 'Subjects for curriculum entries',
            },
        ),
    ]
