# Generated by Django 2.2 on 2019-04-28 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetableapp', '0021_auto_20190428_2044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curriculumentry',
            name='subjects',
        ),
        migrations.RemoveField(
            model_name='curriculumentrysubject',
            name='lecturer',
        ),
    ]
