# Generated by Django 2.2 on 2019-04-28 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetableapp', '0022_auto_20190428_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculumentry',
            name='subjects',
            field=models.ManyToManyField(through='timetableapp.CurriculumEntrySubject', to='timetableapp.Subject', verbose_name='Subject'),
        ),
        migrations.AddField(
            model_name='curriculumentrysubject',
            name='lecturer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='timetableapp.Teacher', verbose_name='Lecturer'),
        ),
    ]
