# Generated by Django 2.2 on 2019-05-04 10:43

from django.db import migrations, models
import django.db.models.deletion
import yearlessdate.models


class Migration(migrations.Migration):

    dependencies = [
        ('timetableapp', '0022_auto_20190504_1040'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formofstudysemester',
            options={'verbose_name': 'Semester date range', 'verbose_name_plural': 'Semester date ranges'},
        ),
        migrations.AlterField(
            model_name='building',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, default=None, max_digits=9, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='formofstudy',
            name='semesters',
            field=models.PositiveSmallIntegerField(default=8, help_text='Total number of semesters, later if you specify fewer Semester date ranges than Number of semesters they will cycle from beginning automatically', verbose_name='Number of semesters'),
        ),
        migrations.AlterField(
            model_name='formofstudysemester',
            name='date_range',
            field=yearlessdate.models.YearlessDateRangeField(verbose_name='Default date range'),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_stream',
            field=models.ForeignKey(blank=True, default=None, help_text='If Parent node is set, this field fills automatically while saving.', null=True, on_delete=django.db.models.deletion.CASCADE, to='timetableapp.GroupStream', verbose_name='Group stream'),
        ),
    ]
