# Generated by Django 2.2 on 2019-04-28 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetableapp', '0023_auto_20190428_2050'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculumEntryTeacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsibility', models.PositiveSmallIntegerField(choices=[(0, 'Lectures'), (1, 'Practices'), (2, 'Laboratory')], default=0, verbose_name='Responsibility')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetableapp.CurriculumEntry', verbose_name='Curriculum entry')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetableapp.Group', verbose_name='Subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetableapp.Teacher', verbose_name='Lecturer')),
            ],
            options={
                'verbose_name': 'Teacher for curriculum entry',
                'verbose_name_plural': 'Teachers for curriculum entries',
                'unique_together': {('entry', 'group', 'responsibility', 'teacher')},
            },
        ),
    ]
