# Generated by Django 2.2 on 2019-04-28 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetableapp', '0024_curriculumentryteacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculumentry',
            name='teachers',
            field=models.ManyToManyField(through='timetableapp.CurriculumEntryTeacher', to='timetableapp.Teacher', verbose_name='Teachers'),
        ),
        migrations.AlterField(
            model_name='curriculumentry',
            name='subjects',
            field=models.ManyToManyField(through='timetableapp.CurriculumEntrySubject', to='timetableapp.Subject', verbose_name='Subjects'),
        ),
    ]
