# Generated by Django 2.2 on 2019-04-28 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetableapp', '0025_auto_20190428_2112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curriculumentrysubject',
            name='lecturer',
        ),
        migrations.AddField(
            model_name='subject',
            name='department',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='timetableapp.Department', verbose_name='Department'),
        ),
    ]
