# Generated by Django 2.2 on 2019-04-29 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetableapp', '0026_auto_20190428_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculumentryteacher',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetableapp.Group', verbose_name='Group'),
        ),
        migrations.AlterUniqueTogether(
            name='curriculumentryteacher',
            unique_together={('entry', 'group', 'responsibility')},
        ),
        migrations.CreateModel(
            name='SemesterSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.PositiveSmallIntegerField(default=0, verbose_name='Semester')),
                ('weeks', models.PositiveSmallIntegerField(default=0, verbose_name='Number of weeks')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetableapp.Group', verbose_name='Curriculum entry')),
            ],
            options={
                'verbose_name': 'Semester schedule',
                'verbose_name_plural': 'Semester schedule',
                'unique_together': {('group', 'semester')},
            },
        ),
    ]
