# Generated by Django 2.2 on 2019-05-04 13:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import timetableapp.models
import timetableapp.settings
import yearlessdate.models


class Migration(migrations.Migration):

    dependencies = [
        ('timetableapp', '0027_auto_20190504_1100'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='building',
            options={'verbose_name': 'building', 'verbose_name_plural': 'buildings'},
        ),
        migrations.AlterModelOptions(
            name='classroom',
            options={'verbose_name': 'classroom', 'verbose_name_plural': 'classrooms'},
        ),
        migrations.AlterModelOptions(
            name='curriculum',
            options={'verbose_name': 'curriculum', 'verbose_name_plural': 'curriculums'},
        ),
        migrations.AlterModelOptions(
            name='curriculumrecord',
            options={'verbose_name': 'curriculum record', 'verbose_name_plural': 'curriculum records'},
        ),
        migrations.AlterModelOptions(
            name='curriculumrecordsubject',
            options={'verbose_name': 'subject for curriculum record', 'verbose_name_plural': 'subjects for curriculum records'},
        ),
        migrations.AlterModelOptions(
            name='curriculumrecordteacher',
            options={'verbose_name': 'teacher for curriculum record', 'verbose_name_plural': 'teachers for curriculum records'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'department', 'verbose_name_plural': 'departments'},
        ),
        migrations.AlterModelOptions(
            name='faculty',
            options={'verbose_name': 'faculty', 'verbose_name_plural': 'faculties'},
        ),
        migrations.AlterModelOptions(
            name='formofstudy',
            options={'ordering': ['priority'], 'verbose_name': 'form of study', 'verbose_name_plural': 'forms of study'},
        ),
        migrations.AlterModelOptions(
            name='formofstudysemester',
            options={'verbose_name': 'semester date range', 'verbose_name_plural': 'semester date ranges'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'group', 'verbose_name_plural': 'groups'},
        ),
        migrations.AlterModelOptions(
            name='groupstream',
            options={'verbose_name': 'group stream', 'verbose_name_plural': 'group streams'},
        ),
        migrations.AlterModelOptions(
            name='groupstreamsemester',
            options={'verbose_name': 'group stream semester', 'verbose_name_plural': 'group stream semesters'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'person', 'verbose_name_plural': 'persons'},
        ),
        migrations.AlterModelOptions(
            name='specialty',
            options={'verbose_name': 'specialty', 'verbose_name_plural': 'specialties'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'subject', 'verbose_name_plural': 'subjects'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'teacher', 'verbose_name_plural': 'teachers'},
        ),
        migrations.AlterModelOptions(
            name='timetablerecording',
            options={'verbose_name': 'timetable recording', 'verbose_name_plural': 'timetable recordings'},
        ),
        migrations.AlterField(
            model_name='building',
            name='address',
            field=models.CharField(blank=True, default=None, max_length=128, null=True, unique=True, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='building',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, default=None, max_digits=9, null=True, verbose_name='latitude'),
        ),
        migrations.AlterField(
            model_name='building',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, default=None, max_digits=9, null=True, verbose_name='longitude'),
        ),
        migrations.AlterField(
            model_name='building',
            name='number',
            field=models.PositiveSmallIntegerField(unique=True, verbose_name='number'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetableapp.Building', verbose_name='building'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='number',
            field=models.PositiveSmallIntegerField(unique=True, verbose_name='number'),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetableapp.GroupStream', verbose_name='group stream'),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='semester',
            field=models.PositiveSmallIntegerField(verbose_name='semester'),
        ),
        migrations.AlterField(
            model_name='curriculumrecord',
            name='curriculum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetableapp.Curriculum', verbose_name='curriculum'),
        ),
        migrations.AlterField(
            model_name='curriculumrecord',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetableapp.Group', verbose_name='group'),
        ),
        migrations.AlterField(
            model_name='curriculumrecord',
            name='independent_work',
            field=models.PositiveSmallIntegerField(verbose_name='amount of independent work'),
        ),
        migrations.AlterField(
            model_name='curriculumrecord',
            name='laboratory',
            field=models.PositiveSmallIntegerField(verbose_name='number of laboratory'),
        ),
        migrations.AlterField(
            model_name='curriculumrecord',
            name='lectures',
            field=models.PositiveSmallIntegerField(verbose_name='number of lectures'),
        ),
        migrations.AlterField(
            model_name='curriculumrecord',
            name='practices',
            field=models.PositiveSmallIntegerField(verbose_name='number of practices'),
        ),
        migrations.AlterField(
            model_name='curriculumrecord',
            name='subjects',
            field=models.ManyToManyField(through='timetableapp.CurriculumRecordSubject', to='timetableapp.Subject', verbose_name='subjects'),
        ),
        migrations.AlterField(
            model_name='curriculumrecord',
            name='teachers',
            field=models.ManyToManyField(through='timetableapp.CurriculumRecordTeacher', to='timetableapp.Teacher', verbose_name='teachers'),
        ),
        migrations.AlterField(
            model_name='curriculumrecordsubject',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetableapp.CurriculumRecord', verbose_name='curriculum record'),
        ),
        migrations.AlterField(
            model_name='curriculumrecordsubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetableapp.Subject', verbose_name='subject'),
        ),
        migrations.AlterField(
            model_name='curriculumrecordteacher',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetableapp.Group', verbose_name='group'),
        ),
        migrations.AlterField(
            model_name='curriculumrecordteacher',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetableapp.CurriculumRecord', verbose_name='curriculum record'),
        ),
    ]
