# Generated by Django 2.2 on 2019-04-29 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetableapp', '0028_teacher_worktime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupstate',
            options={'ordering': ('priority', 'name'), 'verbose_name': 'Group state', 'verbose_name_plural': 'Group states'},
        ),
        migrations.RemoveField(
            model_name='curriculumentry',
            name='semester',
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.PositiveSmallIntegerField(verbose_name='Semester')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetableapp.Group', verbose_name='Group')),
            ],
            options={
                'verbose_name': 'Curriculum entry',
                'verbose_name_plural': 'Curriculum entries',
                'unique_together': {('group', 'semester')},
            },
        ),
    ]
