# Generated by Django 2.2 on 2019-05-04 13:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import timetableapp.models
import timetableapp.settings
import yearlessdate.models


class Migration(migrations.Migration):

    dependencies = [
        ('timetableapp', '0028_auto_20190504_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculumrecordteacher',
            name='responsibility',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Lectures'), (1, 'Practices'), (2, 'Laboratory')], default=0, verbose_name='responsibility'),
        ),
        migrations.AlterField(
            model_name='curriculumrecordteacher',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetableapp.Teacher', verbose_name='teacher'),
        ),
        migrations.AlterField(
            model_name='department',
            name='abbreviation',
            field=models.CharField(blank=True, default=None, max_length=16, null=True, unique=True, verbose_name='abbreviation'),
        ),
        migrations.AlterField(
            model_name='department',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='timetableapp.Faculty', verbose_name='faculty'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='abbreviation',
            field=models.CharField(blank=True, default=None, max_length=16, null=True, unique=True, verbose_name='abbreviation'),
        ),
    ]
