# Generated by Django 2.2 on 2019-04-29 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetableapp', '0029_auto_20190429_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculumentry',
            name='curriculum',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='timetableapp.Curriculum', verbose_name='Curriculum'),
            preserve_default=False,
        ),
    ]
