# Generated by Django 2.2 on 2019-05-04 13:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import timetableapp.models
import timetableapp.settings
import yearlessdate.models


class Migration(migrations.Migration):

    dependencies = [
        ('timetableapp', '0029_auto_20190504_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='formofstudy',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='formofstudy',
            name='priority',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=5, verbose_name='priority'),
        ),
        migrations.AlterField(
            model_name='formofstudy',
            name='semesters',
            field=models.PositiveSmallIntegerField(default=8, help_text='Total number of semesters, later if you specify fewer Semester date ranges than Number of semesters they will cycle from beginning automatically.', verbose_name='number of semesters'),
        ),
    ]
