# Generated by Django 2.2 on 2019-05-04 13:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import timetableapp.models
import timetableapp.settings


class Migration(migrations.Migration):

    dependencies = [
        ('timetableapp', '0031_auto_20190504_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formofstudysemester',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='timetableapp.FormOfStudy', verbose_name='form of study'),
        ),
    ]
