# Generated by Django 2.2 on 2019-05-04 13:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import timetableapp.models
import timetableapp.settings


class Migration(migrations.Migration):

    dependencies = [
        ('timetableapp', '0032_auto_20190504_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_stream',
            field=models.ForeignKey(blank=True, default=None, help_text='If Parent node is set, this field fills automatically while saving.', null=True, on_delete=django.db.models.deletion.CASCADE, to='timetableapp.GroupStream', verbose_name='group stream'),
        ),
        migrations.AlterField(
            model_name='group',
            name='number',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(None, '-'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)], default=None, null=True, verbose_name='number'),
        ),
        migrations.AlterField(
            model_name='group',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='timetableapp.Group', verbose_name='parent node'),
        ),
        migrations.AlterField(
            model_name='groupstream',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='timetableapp.FormOfStudy', verbose_name='form of study'),
        ),
        migrations.AlterField(
            model_name='groupstream',
            name='specialty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='timetableapp.Specialty', verbose_name='specialty'),
        ),
        migrations.AlterField(
            model_name='groupstream',
            name='year',
            field=models.PositiveSmallIntegerField(default=timetableapp.settings.current_year, validators=[timetableapp.models.year_min_value, timetableapp.models.year_max_value], verbose_name='year'),
        ),
        migrations.AlterField(
            model_name='groupstreamsemester',
            name='end_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='groupstreamsemester',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetableapp.GroupStream', verbose_name='group stream'),
        ),
        migrations.AlterField(
            model_name='groupstreamsemester',
            name='semester',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='semester'),
        ),
        migrations.AlterField(
            model_name='groupstreamsemester',
            name='start_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='start date'),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(max_length=128, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(max_length=128, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='middle_name',
            field=models.CharField(max_length=128, verbose_name='middle name'),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='abbreviation',
            field=models.CharField(max_length=16, unique=True, verbose_name='abbreviation'),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='faculty',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='timetableapp.Faculty', verbose_name='faculty'),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='number',
            field=models.PositiveSmallIntegerField(unique=True, verbose_name='number'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='department',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='timetableapp.Department', verbose_name='department'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='department',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='timetableapp.Department', verbose_name='department'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='timetableapp.Person', verbose_name='person'),
        ),
        migrations.AlterField(
            model_name='timetablerecording',
            name='classroom',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='timetableapp.Classroom', verbose_name='classroom'),
        ),
        migrations.AlterField(
            model_name='timetablerecording',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetableapp.Group', verbose_name='group'),
        ),
        migrations.AlterField(
            model_name='timetablerecording',
            name='lesson',
            field=models.PositiveSmallIntegerField(choices=[(1, 'чисельник - пн - 1 заняття'), (2, 'чисельник - пн - 2 заняття'), (3, 'чисельник - пн - 3 заняття'), (4, 'чисельник - пн - 4 заняття'), (5, 'чисельник - пн - 5 заняття'), (33, 'чисельник - вт - 1 заняття'), (34, 'чисельник - вт - 2 заняття'), (35, 'чисельник - вт - 3 заняття'), (36, 'чисельник - вт - 4 заняття'), (37, 'чисельник - вт - 5 заняття'), (65, 'чисельник - ср - 1 заняття'), (66, 'чисельник - ср - 2 заняття'), (67, 'чисельник - ср - 3 заняття'), (68, 'чисельник - ср - 4 заняття'), (69, 'чисельник - ср - 5 заняття'), (97, 'чисельник - чт - 1 заняття'), (98, 'чисельник - чт - 2 заняття'), (99, 'чисельник - чт - 3 заняття'), (100, 'чисельник - чт - 4 заняття'), (101, 'чисельник - чт - 5 заняття'), (129, 'чисельник - пт - 1 заняття'), (130, 'чисельник - пт - 2 заняття'), (131, 'чисельник - пт - 3 заняття'), (132, 'чисельник - пт - 4 заняття'), (133, 'чисельник - пт - 5 заняття'), (161, 'чисельник - сб - 1 заняття'), (162, 'чисельник - сб - 2 заняття'), (163, 'чисельник - сб - 3 заняття'), (164, 'чисельник - сб - 4 заняття'), (165, 'чисельник - сб - 5 заняття'), (257, 'знаменник - пн - 1 заняття'), (258, 'знаменник - пн - 2 заняття'), (259, 'знаменник - пн - 3 заняття'), (260, 'знаменник - пн - 4 заняття'), (261, 'знаменник - пн - 5 заняття'), (289, 'знаменник - вт - 1 заняття'), (290, 'знаменник - вт - 2 заняття'), (291, 'знаменник - вт - 3 заняття'), (292, 'знаменник - вт - 4 заняття'), (293, 'знаменник - вт - 5 заняття'), (321, 'знаменник - ср - 1 заняття'), (322, 'знаменник - ср - 2 заняття'), (323, 'знаменник - ср - 3 заняття'), (324, 'знаменник - ср - 4 заняття'), (325, 'знаменник - ср - 5 заняття'), (353, 'знаменник - чт - 1 заняття'), (354, 'знаменник - чт - 2 заняття'), (355, 'знаменник - чт - 3 заняття'), (356, 'знаменник - чт - 4 заняття'), (357, 'знаменник - чт - 5 заняття'), (385, 'знаменник - пт - 1 заняття'), (386, 'знаменник - пт - 2 заняття'), (387, 'знаменник - пт - 3 заняття'), (388, 'знаменник - пт - 4 заняття'), (389, 'знаменник - пт - 5 заняття'), (417, 'знаменник - сб - 1 заняття'), (418, 'знаменник - сб - 2 заняття'), (419, 'знаменник - сб - 3 заняття'), (420, 'знаменник - сб - 4 заняття'), (421, 'знаменник - сб - 5 заняття')], default=0, verbose_name='lesson number'),
        ),
        migrations.AlterField(
            model_name='timetablerecording',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetableapp.CurriculumRecord', verbose_name='curriculum record'),
        ),
        migrations.AlterField(
            model_name='timetablerecording',
            name='teacher',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='timetableapp.Teacher', verbose_name='teacher'),
        ),
    ]
