# Generated by Django 2.2 on 2019-04-29 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetableapp', '0033_remove_curriculumentry_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculumentryteacher',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetableapp.Teacher', verbose_name='Teacher'),
        ),
        migrations.AlterField(
            model_name='semesterschedule',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetableapp.Group', verbose_name='Group'),
        ),
        migrations.CreateModel(
            name='TimetableEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson', models.PositiveSmallIntegerField(default=0, verbose_name='Number of lesson')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetableapp.CurriculumEntry', verbose_name='Curriculum entry')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetableapp.Group', verbose_name='Group')),
            ],
            options={
                'verbose_name': 'Timetable entry',
                'verbose_name_plural': 'Timetable',
                'unique_together': {('entry', 'group', 'lesson')},
            },
        ),
    ]
