# Generated by Django 2.2 on 2019-04-29 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetableapp', '0036_semesterschedule_startweek'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timetableentry',
            options={'verbose_name': 'Timetable entry', 'verbose_name_plural': 'Timetable entries'},
        ),
    ]
