# Generated by Django 2.2 on 2019-04-29 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetableapp', '0038_building_classroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetableentry',
            name='classroom',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='timetableapp.Classroom', verbose_name='Classroom'),
        ),
        migrations.AlterUniqueTogether(
            name='timetableentry',
            unique_together={('entry', 'group', 'lesson'), ('lesson', 'classroom')},
        ),
    ]
