# Generated by Django 2.2.1 on 2019-05-09 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetableapp', '0038_auto_20190509_0631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curriculumrecordteacher',
            name='subject',
        ),
        migrations.AddField(
            model_name='curriculumrecord',
            name='subject',
            field=models.ForeignKey(blank=True, default=None, help_text='If you leave this field empty, you will able to choose multiple subjects in inline form after saving, but you will not able to assert teacher.', null=True, on_delete=django.db.models.deletion.CASCADE, to='timetableapp.Subject', verbose_name='subject'),
        ),
        migrations.AlterField(
            model_name='curriculumrecord',
            name='subjects',
            field=models.ManyToManyField(related_name='or_subjects', through='timetableapp.CurriculumRecordSubject', to='timetableapp.Subject', verbose_name='subjects'),
        ),
        migrations.AlterField(
            model_name='curriculumrecordteacher',
            name='teacher',
            field=models.ForeignKey(help_text='To assign teacher, you need choose at least one subject.', on_delete=django.db.models.deletion.CASCADE, to='timetableapp.Teacher', verbose_name='teacher'),
        ),
    ]
