# Generated by Django 2.2 on 2019-04-29 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetableapp', '0039_auto_20190429_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetableentry',
            name='teacher',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='timetableapp.Teacher', verbose_name='Teacher'),
        ),
    ]
