# Generated by Django 2.2.1 on 2019-05-09 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetableapp', '0039_auto_20190509_0856'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='curriculumrecord',
            unique_together={('curriculum', 'group', 'subject')},
        ),
    ]
