# Generated by Django 2.2.1 on 2019-05-09 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetableapp', '0040_auto_20190509_0900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curriculumrecord',
            name='subjects',
        ),
        migrations.DeleteModel(
            name='CurriculumRecordSubject',
        ),
    ]
