# Generated by Django 2.2 on 2019-04-29 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetableapp', '0040_timetableentry_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semesterschedule',
            name='startWeek',
        ),
        migrations.RemoveField(
            model_name='semesterschedule',
            name='weeks',
        ),
        migrations.AddField(
            model_name='semesterschedule',
            name='endDate',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='End date'),
        ),
        migrations.AddField(
            model_name='semesterschedule',
            name='startDate',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Start date'),
        ),
    ]
