# Generated by Django 2.2.1 on 2019-05-09 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetableapp', '0041_auto_20190509_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculumrecord',
            name='subjects',
            field=models.ManyToManyField(related_name='or_subjects', to='timetableapp.Subject', verbose_name='subjects'),
        ),
    ]
