# Generated by Django 2.2.1 on 2019-05-09 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetableapp', '0042_curriculumrecord_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculumrecord',
            name='subjects',
            field=models.ManyToManyField(to='timetableapp.Subject', verbose_name='subjects'),
        ),
        migrations.AlterUniqueTogether(
            name='curriculumrecord',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='curriculumrecord',
            name='subject',
        ),
    ]
