# Generated by Django 2.2.1 on 2019-05-11 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetableapp', '0043_auto_20190509_1116'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['-group_stream__year'], 'verbose_name': 'Group object', 'verbose_name_plural': 'groups'},
        ),
        migrations.AlterModelOptions(
            name='groupstream',
            options={'ordering': ['-year'], 'verbose_name': 'Group stream object', 'verbose_name_plural': 'group streams'},
        ),
    ]
