# Generated by Django 2.2.1 on 2019-05-11 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetableapp', '0045_auto_20190511_2023'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='building',
            options={'ordering': ['number'], 'verbose_name': 'Building object', 'verbose_name_plural': 'buildings'},
        ),
        migrations.AlterModelOptions(
            name='classroom',
            options={'ordering': ['building__number', 'number'], 'verbose_name': 'Classroom object', 'verbose_name_plural': 'classrooms'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['abbreviation', 'name'], 'verbose_name': 'Department object', 'verbose_name_plural': 'departments'},
        ),
        migrations.AlterModelOptions(
            name='faculty',
            options={'ordering': ['abbreviation', 'name'], 'verbose_name': 'Faculty object', 'verbose_name_plural': 'faculties'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['first_name', 'middle_name', 'last_name'], 'verbose_name': 'Person object', 'verbose_name_plural': 'persons'},
        ),
        migrations.AlterModelOptions(
            name='specialty',
            options={'ordering': ['abbreviation'], 'verbose_name': 'Specialty object', 'verbose_name_plural': 'specialties'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['name', 'department'], 'verbose_name': 'Subject object', 'verbose_name_plural': 'subjects'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['person__first_name', 'person__middle_name', 'person__last_name'], 'verbose_name': 'Teacher object', 'verbose_name_plural': 'teachers'},
        ),
        migrations.AlterField(
            model_name='classroom',
            name='number',
            field=models.PositiveSmallIntegerField(verbose_name='number'),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='name',
            field=models.CharField(max_length=128, verbose_name='name'),
        ),
        migrations.AlterUniqueTogether(
            name='classroom',
            unique_together={('building', 'number')},
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('name', 'department')},
        ),
    ]
