# Generated by Django 2.2.1 on 2019-05-12 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetableapp', '0048_auto_20190511_2049'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curriculumrecord',
            options={'ordering': ['curriculum', 'group'], 'verbose_name': 'Curriculum record object', 'verbose_name_plural': 'curriculum records'},
        ),
        migrations.AlterField(
            model_name='teacher',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='timetableapp.Department', verbose_name='department'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='timetableapp.Person', verbose_name='person'),
        ),
    ]
