# Generated by Django 2.2.1 on 2019-05-20 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetableapp', '0049_auto_20190512_0803'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetablerecording',
            name='end_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='end date'),
        ),
        migrations.AddField(
            model_name='timetablerecording',
            name='start_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='start date'),
        ),
    ]
