# Generated by Django 2.2.1 on 2019-05-20 13:58

from django.db import migrations
import lesson_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('timetableapp', '0053_auto_20190520_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetablerecording',
            name='lesson',
            field=lesson_field.models.LessonField(default=0, verbose_name='lesson number'),
        ),
    ]
