# Generated by Django 2.2.1 on 2019-05-20 17:02

from django.db import migrations
import lesson_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('timetableapp', '0054_auto_20190520_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetablerecording',
            name='lesson',
            field=lesson_field.models.LessonField(editable=False, verbose_name='lesson number'),
        ),
        migrations.AlterUniqueTogether(
            name='timetablerecording',
            unique_together={('record', 'group', 'lesson', 'classroom'), ('record', 'group', 'lesson'), ('record', 'group', 'lesson', 'teacher')},
        ),
    ]
